ALTER TABLE sys_users AUTO_INCREMENT = 100;

ALTER TABLE sys_roles AUTO_INCREMENT = 100;

ALTER TABLE sys_permissions AUTO_INCREMENT = 10000;

ALTER TABLE sys_dict_type AUTO_INCREMENT = 1000;

ALTER TABLE sys_dict_item AUTO_INCREMENT = 10000;
